dist: trusty

sudo: false

language: php

php:
  - 7.2
  - 7.3

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_failure: true
    include:
        - dist: precise
          php: 7.2
          env: dependencies=lowest
        - php: 7.2
          env: SYMFONY_VERSION=3.4.x
        - php: 7.3
          env: SYMFONY_VERSION=4.0.x stability=beta

before_install:
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi
  - if [ "$stability" != "" ]; then composer config minimum-stability $stability; fi

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction; else composer update --prefer-dist --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
